services:
  prometheus:
    image: prom/prometheus:v3.13.1
    restart: unless-stopped

    extra_hosts:
      - "app-prod:${APP_PRIVATE_IP}"

    volumes:
      - ./monitoring/prometheus/prometheus.prod.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:13.1.0
    restart: unless-stopped

    ports:
      - "3000:3000"

    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro

    depends_on:
      - prometheus

volumes:
  prometheus-data:
  grafana-data: