"""add task ownership

Revision ID: 32721ce95d01
Revises: 505aa916db66
Create Date: 2026-07-22 21:00:59.178882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32721ce95d01'
down_revision: Union[str, Sequence[str], None] = '505aa916db66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_tasks_owner_id'), 'tasks', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_owner_id'), table_name='tasks')
    op.drop_column('tasks', 'owner_id')
    # ### end Alembic commands ###
